version: 0.0
environment_variables:
    plaintext:
        "INPUT_FILE": "saml.yaml"
        "S3_BUCKET": ""
containers:
    LambdaFunctions:
        phases:
            during_build:
                commands:
                    - npm install
                    - npm install @angular/material 
                    - npm build 
                    - aws s3 sync ./dist s3://code43-s3-stack-s3bucket-1d8hdif1vfenc
        artifacts:
            files:
                - post-saml.yaml
                - beta.json